### ISSUE TITLE
Create documentation for maintaining a fork.

### ISSUE THREAD

**Issue by damymetzke** [RoostingGeese/git-gosling#24]
**Is your feature request related to a problem? Please describe.**
When maintaining a fork of a project the command ```$git status``` will compare the local `main` branch with ```origin/main```.
However it will not check ```upstream/main```.

**Describe the solution you'd like**
Create documentation to explain how to test for updates in the upstream repository.

**Comment by HonkingGoose** [comment]
Thanks for the issue report.

The basic problem is that `git status` will straight up lie to you, if you don't first do a `git fetch --all`.

This will be added to the guide for sure, as I see new developers struggle with this all the time.

----

## Git fetch to check for updates to fork and remotes

Use `git fetch --all --prune`, to check for updates on your fork and remotes, `--prune` will remove pointers to branches on the `origin` or `upstream` that are no longer present.

## Check local branches

Use `git branch -vv` to check all your local branches.
You can remove local branches that are *gone* on the remote with `git branch -D name_of_branch_to_remove`.

## Getting a list of all remotes with:

```
$ git remote -vv

origin	https://github.com/RoostingGeese/git-gosling.git (fetch)
origin	https://github.com/RoostingGeese/git-gosling.git (push)
```

## Configuring a remote for a fork

If you are using a fork, you should setup a new remote called `upstream` that points to the upstream project.

```
$ git remote add upstream https://github.com/ORIGINAL_OWNER/ORIGINAL_REPOSITORY.git
```

https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/configuring-a-remote-for-a-fork
