### ISSUE TITLE
Geen rechten om kaartjes aan projectboard toe te voegen.

### ISSUE THREAD

**Issue by jeremyghst** [RoostingGeese/git-gosling#7]
**Zou je mij ook bewerkrechten kunnen geven**
Met bewerkrechten bedoel ik de mogelijkheid om kaartjes aan te maken en aan te passen. 

**Voor het geval dat je morgen graag wil terug vallen op de besproken flow, zet ik hem hieronder voor je weg**:

**Iedereen maakt een eigen repo**
- Git init, git status
- Git add, git commit
- Git add: na een locale aanpassing 
*(Git add -p)*

**Branches**
- Git branch
- Git switch
(Daarna: git switch create)
- Git merg

**Naar Github**
- Werk pushen naar een lege repo op github
- Maak op github iets aan: git pull
- Maak een locale verandering: git push

**Git pull request**

**Comment by HonkingGoose** [comment]
Ik heb je de juiste rechten gegeven nu denk ik, probeer maar een kaartje aan te maken op het bord.

Ik heb de kaartjes aangemaakt en in de juiste volgorde op de backlog gezet.
